/*
Reccito API

Testing MerchantStoresAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package reccitosdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/reccito/reccito-sdk-go"
)

func Test_reccitosdk_MerchantStoresAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MerchantStoresAPIService CreateStore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MerchantStoresAPI.CreateStore(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantStoresAPIService GetStore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.MerchantStoresAPI.GetStore(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantStoresAPIService GetStoreStats", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.MerchantStoresAPI.GetStoreStats(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantStoresAPIService ListStores", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MerchantStoresAPI.ListStores(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantStoresAPIService UpdateStore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.MerchantStoresAPI.UpdateStore(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
